baseURL = "https://atecon.github.io/"
languageCode = "en-us"
title = "atecon's blog"
theme = "blackburn"
canonifyurls = true
paginate = 8
author = "Artur Tarassow"

[taxonomies]
   tag = "tags"
   category = "categories"

[params]
# Shown in the home page
  subtitle = "atecon's blog"
  brand = "atecon"
  # googleAnalytics = "Your Google Analytics tracking ID"
  description = "Economist, Data Scientist, Developer"


[social]
  github="atecon"
  twitter="atecon1"
  stackoverflow="https://stackoverflow.com/users/13028724/atecon"
  xing="Artur_Tarassow"


# sectionPagesMenu = "main"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "Home"
    url = "/"
    #identifier = "home"
    #name = "Home"
    #url = "/"
    #weight = 1
  [[menu.main]]
    identifier = "about"
    name = "About me"
    url = "/about"
    weight = 2
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 3
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    identifier = "research"
    name = "Research"
    url = "/research"
    #parent = "Research"
    weight = 4
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects"
    weight = 5
